.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svg:pyAttributes-github| image:: https://img.shields.io/badge/pyTooling-pyAttributes-323131?logo=github&longCache=true
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/pyTooling/pyAttributes
.. |SHIELD:png:pyAttributes-github| image:: https://raster.shields.io/badge/pyTooling-pyAttributes-323131?logo=github&longCache=true
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/pyTooling/pyAttributes

.. # Sourcecode license
.. |SHIELD:svg:pyAttributes-src-license| image:: https://img.shields.io/pypi/l/pyAttributes?logo=GitHub&label=code%20license
   :alt: Code license
   :height: 22
   :target: Code-License.html
.. |SHIELD:png:pyAttributes-src-license| image:: https://img.shields.io/pypi/l/pyAttributes?logo=GitHub&label=code%20license
   :alt: Code license
   :height: 22
   :target: https://GitHub.com/pyTooling/pyAttributes/blob/main/LICENSE.md

.. # GitHub tag
.. |SHIELD:svg:pyAttributes-tag| image:: https://img.shields.io/github/v/tag/pyTooling/pyAttributes?logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/pyTooling/pyAttributes/tags
.. |SHIELD:png:pyAttributes-tag| image:: https://raster.shields.io/github/v/tag/pyTooling/pyAttributes?logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/pyTooling/pyAttributes/tags

.. # GitHub release
.. |SHIELD:svg:pyAttributes-release| image:: https://img.shields.io/github/v/release/pyTooling/pyAttributes?logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://GitHub.com/pyTooling/pyAttributes/releases/latest
.. |SHIELD:png:pyAttributes-release| image:: https://raster.shields.io/github/v/release/pyTooling/pyAttributes?logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://GitHub.com/pyTooling/pyAttributes/releases/latest

.. # GitHub release date
.. |SHIELD:svg:pyAttributes-date| image:: https://img.shields.io/github/release-date/pyTooling/pyAttributes?logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/pyTooling/pyAttributes/releases
.. |SHIELD:png:pyAttributes-date| image:: https://raster.shields.io/github/release-date/pyTooling/pyAttributes?logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/pyTooling/pyAttributes/releases

.. # GitHub/Libraries dependent projects
.. |SHIELD:svg:pyAttributes-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/pyAttributes
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/pyTooling/pyAttributes/network/dependents
.. |SHIELD:png:pyAttributes-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/pyAttributes
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/pyTooling/pyAttributes/network/dependents

.. # GHA test and coverage
.. |SHIELD:svg:pyAttributes-gha-test| image:: https://img.shields.io/github/workflow/status/pyTooling/pyAttributes/Unit%20Testing,%20Coverage%20Collection,%20Package,%20Release,%20Documentation%20and%20Publish?label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/pyTooling/pyAttributes/actions?query=workflow%3A%22Unit%20Testing,%20Coverage%20Collection,%20Package,%20Release,%20Documentation%20and%20Publish%22
.. |SHIELD:png:pyAttributes-gha-test| image:: https://img.shields.io/github/workflow/status/pyTooling/pyAttributes/Unit%20Testing,%20Coverage%20Collection,%20Package,%20Release,%20Documentation%20and%20Publish?label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/pyTooling/pyAttributes/actions?query=workflow%3A%22Unit%20Testing,%20Coverage%20Collection,%20Package,%20Release,%20Documentation%20and%20Publish%22

.. # Codacy - quality
.. |SHIELD:svg:pyAttributes-codacy-quality| image:: https://img.shields.io/codacy/grade/08ef744c0b70490289712b02a7a4cebe?logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/manual/pyTooling/pyAttributes
.. |SHIELD:png:pyAttributes-codacy-quality| image:: https://raster.shields.io/codacy/grade/08ef744c0b70490289712b02a7a4cebe?logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/manual/pyTooling/pyAttributes

.. # Codacy - coverage
.. |SHIELD:svg:pyAttributes-codacy-coverage| image:: https://img.shields.io/codacy/coverage/08ef744c0b70490289712b02a7a4cebe?logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/manual/pyTooling/pyAttributes
.. |SHIELD:png:pyAttributes-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/08ef744c0b70490289712b02a7a4cebe?logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/manual/pyTooling/pyAttributes

.. # Codecov - coverage
.. |SHIELD:svg:pyAttributes-codecov-coverage| image:: https://img.shields.io/codecov/c/github/pyTooling/pyAttributes
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/pyTooling/pyAttributes
.. |SHIELD:png:pyAttributes-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/pyTooling/pyAttributes
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/pyTooling/pyAttributes

.. # Libraries - source rank
.. |SHIELD:svg:pyAttributes-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/pyAttributes
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/pyTooling/pyAttributes/sourcerank
.. |SHIELD:png:pyAttributes-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/pyAttributes
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/pyTooling/pyAttributes/sourcerank

.. # PyPI tag
.. |SHIELD:svg:pyAttributes-pypi-tag| image:: https://img.shields.io/pypi/v/pyAttributes?logo=PyPI
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyAttributes/
.. |SHIELD:png:pyAttributes-pypi-tag| image:: https://raster.shields.io/pypi/v/pyAttributes?logo=PyPI
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyAttributes/

.. # PyPI project status
.. |SHIELD:svg:pyAttributes-pypi-status| image:: https://img.shields.io/pypi/status/pyAttributes?logo=PyPI
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:pyAttributes-pypi-status| image:: https://raster.shields.io/pypi/status/pyAttributes?logo=PyPI
   :alt: PyPI - Status
   :height: 22

.. # PyPI Python versions
.. |SHIELD:svg:pyAttributes-pypi-python| image:: https://img.shields.io/pypi/pyversions/pyAttributes?logo=PyPI
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:pyAttributes-pypi-python| image:: https://raster.shields.io/pypi/pyversions/pyAttributes?logo=PyPI
   :alt: PyPI - Python Version
   :height: 22

.. # Libraries - status
.. |SHIELD:svg:pyAttributes-lib-status| image:: https://img.shields.io/librariesio/release/pypi/pyAttributes
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/pyTooling/pyAttributes
.. |SHIELD:png:pyAttributes-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/pyAttributes
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/pyTooling/pyAttributes

.. # Requires - status
.. |SHIELD:svg:pyAttributes-req-status| image:: https://img.shields.io/requires/github/pyTooling/pyAttributes
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/pyTooling/pyAttributes/requirements/?branch=main
.. |SHIELD:png:pyAttributes-req-status| image:: https://raster.shields.io/requires/github/pyTooling/pyAttributes
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/pyTooling/pyAttributes/requirements/?branch=main

.. # Documentation license
.. |SHIELD:svg:pyAttributes-doc-license| image:: https://img.shields.io/badge/doc%20license-CC--BY%204.0-green
   :alt: Documentation License
   :height: 22
   :target: Doc-License.html
.. |SHIELD:png:pyAttributes-doc-license| image:: https://img.shields.io/badge/doc%20license-CC--BY%204.0-green
   :alt: Documentation License
   :height: 22
   :target: https://GitHub.com/pyTooling/pyAttributes/blob/main/doc/Doc-License.rst

.. # GHPages - read now
.. |SHIELD:svg:pyAttributes-ghp-doc| image:: https://img.shields.io/badge/doc-read%20now%20%E2%9E%9A-blueviolet
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://pyTooling.GitHub.io/pyAttributes/
.. |SHIELD:png:pyAttributes-ghp-doc| image:: https://img.shields.io/badge/doc-read%20now%20%E2%9E%9A-blueviolet
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://pyTooling.GitHub.io/pyAttributes/
